---
- name: install nginx packages
  package:
    name: '{{ nginx_packages }}'
    state: present

- name: set up /var/www/tmp
  file:
    path: /var/www/tmp
    state: directory
    mode: '0777'
    owner: www
    group: www

- name: create nginx directories
  file:
    path: "/etc/nginx/{{ item }}"
    state: directory
    owner: root
    group: wheel
    mode: '0755'
  with_items: ["configs", "sites-available", "sites-enabled"]

- name: copy nginx config
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: wheel
    mode: '0644'
  notify: restart nginx

- name: copy nginx sub-configs
  copy:
    src: configs/
    dest: /etc/nginx/configs/
    owner: root
    group: wheel
    mode: '0644'
  notify: restart nginx

- name: create auth-proxy config
  template:
    src: auth-proxy.conf.j2
    dest: /etc/nginx/configs/auth-proxy.conf
    owner: root
    group: wheel
    mode: '0640'
  notify: restart nginx

- name: setup nginx-ldap-auth
  git:
    repo: https://github.com/nginxinc/nginx-ldap-auth
    dest: '/usr/local/libexec/nginx-ldap-auth'

- name: create nginx-ldap-auth service
  copy:
    src: nginx_ldap_auth
    dest: /etc/rc.d/nginx_ldap_auth
    mode: 755
    owner: root
    group: wheel
  notify: restart nginx-ldap-auth service

- name: enable nginx-ldap-auth service
  service:
    name: nginx_ldap_auth
    state: started
    enabled: true

- name: create site configs
  template:
    src: "{{ item }}"
    dest: "/etc/nginx/sites-available/{{ item | basename | regex_replace('\\.j2$', '') }}"
    owner: root
    group: wheel
    mode: '0644'
  notify: restart nginx
  with_items: "{{ lookup('fileglob', '../templates/sites-available/*.conf.j2') }}"

- name: create extra site configs
  template:
    src: "{{ item }}"
    dest: "/etc/nginx/sites-available/{{ item | basename | regex_replace('\\.j2$', '') }}"
    owner: root
    group: wheel
    mode: '0644'
  notify: restart nginx
  with_items: '{{ nginx_extra_site_configs }}'

- name: start and enable nginx
  service:
    name: nginx
    state: started
    enabled: true

- name: flush_handlers
  meta: flush_handlers
